// pages/index.js
export { default as Recipes } from './Recipes/Recipes'
export { default as Supplies } from './Supplies/Supplies'
export { default as ExpiringSupply } from './Supplies/ExpiringSupply'
export { default as MachinesMaintenance } from './Machines/MachinesMaintenance'
export { default as OrdersProviders } from './Providers/OrdersProviders'
export { default as ProductionEfficiencies } from './Supplies/ProductionEfficiencies'
export { default as Providers } from './Providers/Providers'
export { default as QualityAndPunctualityReport } from './Providers/QualityAndPunctualityReport'
export { default as SuppliesWithLowStock } from './Supplies/SuppliesWithLowStock'
export { default as Users } from './Users/Users'
export { default as WasteReports } from './Supplies/WasteReports'
export { default as StocksUsage } from './Supplies/StocksUsage'
